import { Monster } from '@/interfaces/monster';

export const MONSTERS = [
  { name: '草食龍', icon: '/images/monsters/aptonoth.png' },
  { name: '迅猛龍王', icon: '/images/monsters/velocidrome.png' },
  { name: '搔鳥', icon: '/images/monsters/kulu-ya-ku.png' },
  { name: '怪鳥', icon: '/images/monsters/yian-kut-ku.png' },
  { name: '野豬王', icon: '/images/monsters/bulldrome.png' },
  { name: '毒妖鳥', icon: '/images/monsters/pukei-pukei.png' },
  { name: '背甲龍', icon: '/images/monsters/apceros.png' },
  { name: '狗龍王', icon: '/images/monsters/great-jaggi.png' },
  { name: '水獸', icon: '/images/monsters/royal-ludroth.png' },
  { name: '青熊獸', icon: '/images/monsters/arzuros.png' },
  { name: '彩鳥', icon: '/images/monsters/qurupeco.png' },
  { name: '青怪鳥', icon: '/images/monsters/blue-yian-kut-ku.png' },
  { name: '轟龍', icon: '/images/monsters/tigrex.png' },
  { name: '一角龍', icon: '/images/monsters/monoblos.png' },
  { name: '浮空龍', icon: '/images/monsters/paolumu.png' },
  { name: '岩龍', icon: '/images/monsters/basarios.png' },
  { name: '黑狼鳥', icon: '/images/monsters/yian-garuga.png' },
  { name: '迅龍', icon: '/images/monsters/nargacuga.png' },
  { name: '雌火龍', icon: '/images/monsters/rathian.png' },
  { name: '波波', icon: '/images/monsters/popo.png' },
  { name: '桃毛獸王', icon: '/images/monsters/congalala.png' },
  { name: '眠狗龍王', icon: '/images/monsters/great-baggi.png' },
  { name: '奇猿狐', icon: '/images/monsters/kecha-wacha.png' },
  { name: '毒怪鳥', icon: '/images/monsters/gypceros.png' },
  { name: '冰鮫鯊', icon: '/images/monsters/zamtrios.png' },
  { name: '影蜘蛛', icon: '/images/monsters/nerscylla.png' },
  { name: '土砂龍', icon: '/images/monsters/barroth.png' },
  { name: '飛雷龍', icon: '/images/monsters/tobi-kadachi.png' },
  { name: '奇怪龍', icon: '/images/monsters/khezu.png' },
  { name: '紅怪龍', icon: '/images/monsters/red-khezu.png' },
  { name: '白兔獸', icon: '/images/monsters/lagombi.png' },
  { name: '冰土砂龍', icon: '/images/monsters/jade-barroth.png' },
  { name: '蠻顎龍', icon: '/images/monsters/anjanath.png' },
  { name: '巨獸', icon: '/images/monsters/gammoth.png' },
  { name: '雷狼龍', icon: '/images/monsters/zinogre.png' },
  { name: '冰牙龍', icon: '/images/monsters/barioth.png' },
  { name: '風漂龍', icon: '/images/monsters/legiana.png' },
  { name: '毒猛龍王', icon: '/images/monsters/iodrome.png' },
  { name: '痺猛龍王', icon: '/images/monsters/gendrome.png' },
  { name: '砂龍王', icon: '/images/monsters/cephadrome.png' },
  { name: '白猿狐', icon: '/images/monsters/ash-kecha-wacha.png' },
  { name: '紫毒鳥', icon: '/images/monsters/purple-gypceros.png' },
  { name: '綠迅龍', icon: '/images/monsters/green-nargacuga.png' },
  { name: '角龍', icon: '/images/monsters/diablos.png' },
  { name: '黑角龍', icon: '/images/monsters/black-diablos.png' },
  { name: '白一角龍', icon: '/images/monsters/white-monoblos.png' },
  { name: '紅彩鳥', icon: '/images/monsters/crimson-qurupeco.png' },
  { name: '泡狐龍', icon: '/images/monsters/mizutsune.png' },
  { name: '海龍', icon: '/images/monsters/lagiacrus.png' },
  { name: '爆錘龍', icon: '/images/monsters/uragaan.png' },
  { name: '黑轟龍', icon: '/images/monsters/brute-tigrex.png' },
  { name: '紫水獸', icon: '/images/monsters/purple-ludroth.png' },
  { name: '桃岩龍', icon: '/images/monsters/ruby-basarios.png' },
  { name: '鎧龍', icon: '/images/monsters/gravios.png' },
  { name: '骸蜘蛛', icon: '/images/monsters/shrouded-nerscylla.png' },
  { name: '綠毛獸王', icon: '/images/monsters/emerald-congalala.png' },
  { name: '黑鎧龍', icon: '/images/monsters/black-gravios.png' },
  { name: '白海龍', icon: '/images/monsters/ivory-lagiacrus.png' },
  { name: '碎龍', icon: '/images/monsters/brachydios.png' },
  { name: '滅盡龍', icon: '/images/monsters/nergigante.png' },
  { name: '電龍', icon: '/images/monsters/astalos.png' },
  { name: '斬龍', icon: '/images/monsters/glavenus.png' },
  { name: '爆鱗龍', icon: '/images/monsters/bazelgeuse.png' },
  { name: '風牙龍', icon: '/images/monsters/sand-barioth.png' },
  { name: '恐暴龍', icon: '/images/monsters/deviljho.png' },
  { name: '獄狼龍', icon: '/images/monsters/stygian-zinogre.png' },
  { name: '千刃龍', icon: '/images/monsters/seregios.png' },
  { name: '火龍', icon: '/images/monsters/rathalos.png' },
  { name: '蒼火龍', icon: '/images/monsters/azure-rathalos.png' },
  { name: '櫻火龍', icon: '/images/monsters/pink-rathian.png' },
  { name: '雷顎龍', icon: '/images/monsters/fulgur-anjanath.png' },
  { name: '白疾風', icon: '/images/monsters/silverwind-nargacuga.png' },
  { name: '金雷公', icon: '/images/monsters/thunderlord-zinogre.png' },
  { name: '鏖魔', icon: '/images/monsters/bloodbath-diablos.png' },
  { name: '荒鉤爪', icon: '/images/monsters/grimclaw-tigrex.png' },
  { name: '紫毒姬', icon: '/images/monsters/dreadqueen-rathian.png' },
  { name: '麒麟', icon: '/images/monsters/kirin.png' },
  { name: '炎王龍', icon: '/images/monsters/teostra.png' },
  { name: '金獅子', icon: '/images/monsters/rajang.png' },
  { name: '鋼龍', icon: '/images/monsters/kushala-daora.png' },
  { name: '冰呪龍', icon: '/images/monsters/velkhana.png' },
  { name: '加爾克', icon: '/images/monsters/palamute-normal.png' },
  { name: '加爾克(火)', icon: '/images/monsters/palamute-fire.png' },
  { name: '加爾克(水)', icon: '/images/monsters/palamute-water.png' },
  { name: '加爾克(電)', icon: '/images/monsters/palamute-thunder.png' },
  { name: '加爾克(冰)', icon: '/images/monsters/palamute-ice.png' },
  { name: '加爾克(龍)', icon: '/images/monsters/palamute-dragon.png' },
  { name: '青電主電龍', icon: '/images/monsters/boltreaver-astalos.png' },
  { name: '燼滅刃斬龍', icon: '/images/monsters/hellblade-glavenus.png' },
  { name: '銀嶺巨獸', icon: '/images/monsters/elderfrost-gammoth.png' },
  { name: '天眼泡狐龍', icon: '/images/monsters/soulseer-mizutsune.png' },
  { name: '冰麒麟', icon: '/images/monsters/oroshi-kirin.png' },
];

export const UNRELEASED_MONSTERS = ['銀火龍', '金火龍'];

export const UNKNOWN_MONSTER = {
  id: '0',
  name: '未知',
  icon: '/images/monsters/unknown.png',
} as Monster;

export const DEFAULT_MONSTER_ICON = '/images/monsters/unknown.png';
